version: '3.4'
services:
    localstack:
        image: localstack/localstack
        container_name: localstack
        network_mode: bridge
        environment: 
          - DATA_DIR=tmp/localstack/data # data persistent for Kinesis, DynamoDB, Elasticsearch, S3, Secretsmanager, SSM, SQS, SNS            
          
        ports:
            - 4566:4566
        volumes:
            - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
            - /var/run/docker.sock:/var/run/docker.sock

networks:
    default:
        name: localstack
        