name: 'Sample Workflow'
on:
  workflow_dispatch:
jobs:
  sample-job:    
    name: Sample Job
    runs-on: ubuntu-latest
    steps:

      - id: get-tempDir
        run: |
          echo "::set-output name=tempDir::$(date +%s)"        
        
      - name: create-a-temp-working-folder
        run: |
          tempDir=${{ steps.get-timestamp.outputs.tempDir }}
          sudo mkdir -p $tempDir
          
      - name: create-a-file-in-tempDir
        run: |
          cd $tempDir 
          echo "Hello world!" >> test.txt
      
      - name: display-the-content-of-the-working-file
        run: |
          cd $tempDir 
          cat test.txt
          
      - name: remove-tempDir
        run: |
          pwd
          ls
          sudo rm -R *
          pwd
          ls
          
