name: 'Sample Workflow'
on:
  workflow_dispatch:
jobs:
  sample-job:
    name: Sample Job
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
      
      - name: download tree util
        run: sudo apt-get install tree
      
      - name: display code directory tree
        run: |
          cd $GITHUB_WORKSPACE
          pwd
          ls -a
