name: 'Sample Workflow'
on:
  workflow_dispatch:
jobs:
  sample-job:    
    name: Sample Job
    runs-on: ubuntu-latest
    steps:
#       - name: check out
#         uses: actions/checkout@v3
        
      - id: get-timestamp
        run: |
          echo "::set-output name=timestamp::$(date +%s)"
          echo "$(date +%s)"
      - name: get-tempDir
        run: echo ${{env.tempDir}}
        
      - name: create-a-temp-working-folder
        run: |
          tempDir="$GITHUB_WORKSPACE/${{steps.get-timestamp.outputs.timestamp}}"
          sudo mkdir -p $tempDir
          
      - name: create-a-file-in-tempDir
        run: |
          cd $tempDir 
          echo "Hello world!" >> test.txt
      
      - name: display-the-content-of-the-working-file
        run: |
          cd $tempDir 
          cat test.txt
      - name: remove-tempDir
        run: |
          sudo rm -R $tempDir
          
#       - name: display-timestamp
#         run: echo ${{env.timestamp}}
        
#       - name: download tree util
#         run: sudo apt-get install tree
      
#       - name: display code directory tree
#         run: |
#           cd $GITHUB_WORKSPACE
#           pwd
#           ls -a
#           tree -L 2
#       - name: display-timestamp-again
#         run: echo ${{env.timestamp}}
