
# this workflow simulate ADO build variables
name: 'Test Workflow'
on:
  workflow_dispatch:
  
env:
  GITHUB_TOKEN: ${{ secrets.GHA_TOKEN }}
  
jobs:
  sample-job:    
    name: Sample Job
    runs-on: ubuntu-latest
    steps:
      - id: test
        run: |
          echo "github.sha = ${{ github.sha }}"  
          echo "github.run_id = ${{ github.run_id }}"
          echo "github.run_number = ${{ github.run_number }}"
          echo "job.container.id = ${{ job.container.id }}"
          echo "GITHUB_JOB = $GITHUB_JOB"
          echo "GITHUB_RUN_ID = $GITHUB_RUN_ID"
          job_url="https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs"
          echo $job_url
          #curl -s -H "Authorization: Bearer ${{ env.GITHUB_TOKEN}} $job_url
          #job_id=$(curl -s -H "Authorization: token ${{ env.GITHUB_TOKEN}} $job_url | jq -r '.jobs[] | .id')
          #echo "job_id = $job_id"
