
# this workflow simulate ADO build variables
name: 'Test Workflow'
on:
  workflow_dispatch:
jobs:
  sample-job:    
    name: Sample Job
    runs-on: ubuntu-latest
    steps:
      - id: test
        run: |
          echo "github.sha = ${{ github.sha }}"  
          echo "github.run_id = ${{ github.run_id }}"
          echo "github.run_number = ${{ github.run_number }}"
          echo "job.container.id = ${{ job.container.id }}"
          echo "GITHUB_JOB = $GITHUB_JOB"
          echo "GITHUB_RUN_ID = $GITHUB_RUN_ID"
          GITHUB_BASEURL=https://api.github.com
          GITHUB_API="/repos/${INPUT_REPOSITORY:-${GITHUB_REPOSITORY}}/actions/runs/${INPUT_RUN_ID:-${GITHUB_RUN_ID}}/jobs"
          eval "$(curl --get -Ss -H "Authorization: token ${INPUT_GITHUB_TOKEN}" -H "Accept: application/vnd.github.v3+json" "${GITHUB_BASEURL}${GITHUB_API}?per_page=${INPUT_PER_PAGE:-30}" \
          | jq -r --arg job_name "${INPUT_JOB_NAME}" '.jobs | map(select(.name == $job_name)) | .[0] | @sh "job_id=\(.id) html_url=\(.html_url)"')"
          echo "job_id = ${job_id}"
